### ISSUE TITLE
indentation in the enabled_plugins section of settings.yml is missed

### ISSUE THREAD

**Issue by return42** [WhateverItWorks/my-SearXNG-Docker-Compose#1]
https://github.com/WhateverItWorks/my-SearXNG-Docker-Compose/blob/c79b1efd0290fd69432981a92542184875f73206/searxng/settings.yml#L28-L35

**Comment by xbdmHQ** [comment]
?

**Comment by return42** [comment]
Do you know YAML syntax https://yaml.org/spec/1.2.0/#id2559116

**Comment by xbdmHQ** [comment]
?
